### ISSUE TITLE
cli: static sitemap generation 

### ISSUE THREAD

**Issue by jirikuncar** [inveniosoftware/flask-sitemap#13]
Create command line interface (`flask_sitemap/cli.py:Sitemap`) to generate static sitemap. (see https://github.com/inveniosoftware/flask-sitemap/issues/12#issuecomment-72537093 by @NikhilKalige)

- [x] use `Flask-Script` or `click`

**Comment by NikhilKalige** [comment]
```
@manager.command
def sitemap():
    app_instance.config["SERVER_NAME"] = "atom.shortcircuits.io"
    sitemap = Sitemap(app=app_instance)

    @app_instance.route('/package/<name>')
    def package(name):
        pass

    @app_instance.route("/")
    def index():
        pass

    @app_instance.route('/search')
    def search():
        pass

    @sitemap.register_generator
    def package_urls():
        import datetime
        from app.packages.models import Package, Downloads

        yield 'index', {}, datetime.datetime.today().date().isoformat(), "daily", 1
        yield 'search', {}, datetime.datetime.today().date().isoformat(), "daily", 0.5

        package_list = Package.query.all()
        for item in package_list:
            latest = item.downloads.order_by(Downloads.date.desc()).first()
            time = latest.date.date().isoformat() if latest is not None else ""
            yield 'package', {'name': item.name}, time, "daily", 0.5

    out = sitemap.sitemap()
    if not os.path.exists(SITEMAP_DIR):
        os.makedirs(SITEMAP_DIR)

    f = open(os.path.join(SITEMAP_DIR, SITEMAP_NAME), 'w')
    f.write(out)
    f.close()
```

i used it like this.. would a PR along this terms ok?

**Comment by jirikuncar** [comment]
What about using `Command` from *Flask-Script* (see [example](https://github.com/smurfix/flask-script/blob/master/flask_script/commands.py#L428-L436)).

**Comment by NikhilKalige** [comment]
That would work.. i was looking at adding a few config settings for output dir ... I am willing to make a PR. I was looking at flask-migrate as to how to use flask-script. I just wanted to know if you are willing a accept a PR before i start

**Comment by jirikuncar** [comment]
@NikhilKalige as long as you agree to donate this (and any future) contributions to our Flask-Menu package under the terms of the Revised BSD Licence.

I would like to just ask you to have a look on our [coding standards](https://github.com/inveniosoftware/flask-sitemap/blob/master/.travis.yml#L25-L27) and [test coverage](https://github.com/inveniosoftware/flask-sitemap/blob/master/.travis.yml#L30).

**Comment by NikhilKalige** [comment]
Yeah sure... i am bad at writing tests. :) but will make an effort
