### ISSUE TITLE
tests: python setup.py test not working

### ISSUE THREAD

**Issue by NikhilKalige** [inveniosoftware/flask-sitemap#15]
I am having some issues running the tests... I cant install the right packages.. Can you please consider adding requirements.txt. I am not familiar with setup.py, so not sure whether you need it. 

I am also getting a error as ```Theme Error```. So getting a versionconflict for coverage

**Comment by jirikuncar** [comment]
You can use `tox` to running tests.

**Comment by jirikuncar** [comment]
- http://pytest.org/latest/goodpractises.html#integration-with-setuptools-test-commands
