### ISSUE TITLE
UnicodeDecodeError getting gziped sitemap

### ISSUE THREAD

**Issue by chriseeu** [inveniosoftware/flask-sitemap#20]
Hi,
with flask 0.10.1 an UnicodeDecodeError happens if you try to get a gezipped sitemap.
gzip_response() function does not set the application/octet-stream content type 

Probably, the problem can be fixed by adding 
response.headers["Content-Type"] = "application/octet-stream"

Regards,
Chris

**Comment by jirikuncar** [comment]
Hi @chriseeu, can you please submit a PR with your patch and test case? Thanks
